[package]
name = "shellexec"
version = "0.1.1"
edition = "2021"

[dependencies.windows]
version = "0.58.0"
features = ["Win32_System_Threading", "Win32_Security", "Win32_Foundation", "Win32_UI_WindowsAndMessaging"]
shadow-rs = "0.35.2"
